### ISSUE TITLE
Problem with setting CRAWLER_JOB_TIMEOUT_SEC in env - log: "Expected number, received string"

### ISSUE THREAD

**Issue by Deathproof76** [MohamedBassem/hoarder-app#134]
Hi, really great project! Thank you very much for sharing!

I tried to change the crawler timeouts via environment in the compose.yaml, but I can't seem to find a way without it being interpreted as a string. Upon starting the stack the workers log outputs the following errors:

```
hoarder-workers-1      | 
hoarder-workers-1      | > @hoarder/workers@0.1.0 start:prod /app/apps/workers
hoarder-workers-1      | > tsx index.ts
hoarder-workers-1      | 
hoarder-workers-1      | /app/apps/workers/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:43
hoarder-workers-1      |                 const error = new ZodError_1.ZodError(ctx.common.issues);
hoarder-workers-1      |                               ^
hoarder-workers-1      | 
hoarder-workers-1      | ZodError: [
hoarder-workers-1      |   {
hoarder-workers-1      |     "code": "invalid_type",
hoarder-workers-1      |     "expected": "number",
hoarder-workers-1      |     "received": "string",
hoarder-workers-1      |     "path": [
hoarder-workers-1      |       "CRAWLER_JOB_TIMEOUT_SEC"
hoarder-workers-1      |     ],
hoarder-workers-1      |     "message": "Expected number, received string"
hoarder-workers-1      |   },
hoarder-workers-1      |   {
hoarder-workers-1      |     "code": "invalid_type",
hoarder-workers-1      |     "expected": "number",
hoarder-workers-1      |     "received": "string",
hoarder-workers-1      |     "path": [
hoarder-workers-1      |       "CRAWLER_NAVIGATE_TIMEOUT_SEC"
hoarder-workers-1      |     ],
hoarder-workers-1      |     "message": "Expected number, received string"
hoarder-workers-1      |   }
hoarder-workers-1      | ]
```

Part of my compose.yml:

```
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:latest
    restart: unless-stopped
    volumes:
      - /mnt/Dockerspace/hoarder/web:/data
    environment:
      REDIS_HOST: redis
      CRAWLER_JOB_TIMEOUT_SEC: 120
      CRAWLER_NAVIGATE_TIMEOUT_SEC: 60
```

Also tried via env_file

```
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/Dockerspace/hoarder/web:/data
```

containing

```
      CRAWLER_JOB_TIMEOUT_SEC=120
      CRAWLER_NAVIGATE_TIMEOUT_SEC=60
```
resulting in the same error.

**Comment by MohamedBassem** [comment]
Hi, this was indeed a bug that I thought I fixed. Are you on the latest release? You can check from admin panel of the web UI

**Comment by Deathproof76** [comment]
I was on ghcr.io/mohamedbassem/hoarder-web:latest, ghcr.io/mohamedbassem/hoarder-workers:latest. 
The admin panel actually showed that a newer release was available so I downed and removed the stack and pulled :0.13.1. 
Started the stack without setting TIMEOUT_SEC in env. Admin shows Server Version 0.13.1. 

Retried setting in the compose.yaml via:

```
    environment:
      REDIS_HOST: redis
      CRAWLER_JOB_TIMEOUT_SEC: 120
      CRAWLER_NAVIGATE_TIMEOUT_SEC: 60
```

and restarted the stack but the error remains.

**Comment by MohamedBassem** [comment]
@Deathproof76 sorry about that. I thought I fixed them but apparently I didn't. Pushed the fix now, the docker containers take some time to build (~40mins) once they are built, you can go back to latest and the problem will be fixed. Sorry about that!

**Comment by Deathproof76** [comment]
You don't have to be sorry for anything mate! 😄 Honestly, thank you very much for this fantastic app and all the effort!
